services:

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    #image: docker/mcp-gateway:latest
    image: docker/mcp-gateway:v2
    ports:
      - 9011:9011
    use_api_socket: true    
    command:
      - --port=9011
      - --transport=streaming
      - --verbose
      - --catalog=/mcp/catalog.yaml
      - --servers=mcp-rag,mcp-tesco

    configs:
      - source: catalog.yaml
        target:
          /mcp/catalog.yaml

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./catalog.yaml:/mcp/catalog.yaml

    depends_on:
      mcp-rag:
        condition: service_healthy
      mcp-tesco:
        condition: service_healthy        

  mcp-rag:
    build:
      context: mcp-rag-server
      dockerfile: Dockerfile
    ports:
      - 6060:6060
    environment:
      HTTP_PORT: 6060
      LIMIT: 0.5
      MAX_RESULTS: 3    

    volumes:
      - ./mcp-rag-server/data:/app/data      

    models:
      embeddings:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_EMBEDDINGS_MODEL
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-tesco:
    build:
      context: mcp-tesco-server
      dockerfile: Dockerfile    
    ports:
      - 7070:7070      
    environment:
      MCP_HTTP_PORT: 7070
    
    volumes:
      - ./mcp-tesco-server/data:/app/data

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7070/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # http://host.docker.internal:9011
  # Transport Type: Streamable HTTP
  # URL: http://mcp-gateway:9011/mcp
  # Connection Type: Via Proxy
  # Use the provided URL in the logs to connect to the MCP Inspector
  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    command: ["--config", "/app/mcp.json"]
    ports:
      - 6274:6274
      - 6277:6277
    environment:
      HOST: 0.0.0.0
      ALLOWED_ORIGINS: "http://0.0.0.0:6274,http://localhost:6274"
      MCP_AUTO_OPEN_ENABLED: false
    depends_on:
      - mcp-gateway


configs:
  catalog.yaml:
    content: |
      registry:
        mcp-rag:
          remote:
            url: "http://mcp-rag:6060/mcp"
            transport_type: http

        mcp-tesco:
          remote:
            url: "http://mcp-tesco:7070/mcp"
            transport_type: http

models:
  # tools:
  #   model: hf.co/menlo/jan-nano-gguf:q4_k_m
  chat:
    model: ai/qwen2.5:3B-F16
  embeddings:
    model: ai/mxbai-embed-large:latest